In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from math import sqrt, pi, exp
%matplotlib inline

In [2]:
k = 5            # Archive size
m = 3            # New solutions
n = 3            # Dimension
si = 0.5         # Evaporation rate
q = 0.3

In [3]:
# Define cost function  
def Cost(s):
  n = 3
  cost_value = (np.sum(s)-n)**2
  return cost_value

In [4]:
# Calculating selection probability vector
weight_vector = np.zeros([k])
const_1 = 1/q/k/(sqrt(2*pi))
const_2 = 1/2/q/q/k/k
for i in range(1,k+1):
  weight_vector[i-1] = const_1*exp(const_2*(-1)*(i-1))
sel_prob = weight_vector/(np.sum(weight_vector))
sel_prob.sort()
sel_prob

array([0.12212052, 0.15251008, 0.19046204, 0.2378583 , 0.29704907])

In [5]:
np.sum(sel_prob)

1.0

In [6]:
# Roulette Wheel Selection based on selection probability vector
def RouletteWheelSelection(p_vector):
  r = np.random.uniform(0, 1)
  acc = 0
  idx = -1
  while acc < r: 
    idx += 1 
    acc += p_vector[idx] 
  return idx

In [7]:
for i in range(1, k+1):
  print(i)

1
2
3
4
5


In [8]:
                                                    # Create global matrix for calculation
pop = np.zeros([k+m, n+1])
                                                    # Init k solutions
pop[0:k, 0:n] = np.random.uniform(0, 1, [k, n]) 
                                                    # Calculate fitness values
for i in range(0,k):
  pop[i, n] = Cost(pop[i, 0:n])
                                                    # Sorting k solutions in descending order
pop[0:k] = pop[0:k][np.argsort(-1*pop[0:k, n])]
                                                    
#---------------------------------------------------# Construct m new solutions based-on k solutions

for i in range(k,k+m):
  for j in range(0,n):
                                                    # Choose a based-solution among k solutions
    index = RouletteWheelSelection(sel_prob)
                                                    # Calculate expectation and standard deviation 
    mu = pop[index, j]
    sigma = si * (np.sum(np.absolute(np.subtract(pop[0:k, j], mu)))/(k-1))
                                                    # Calculate S_ij
    pop[i,j] = np.random.normal(mu, sigma)
                                                    # Calculate fitness values
  pop[i, n] = Cost(pop[i, 0:n])                                                    
                                                    # Sorting k+m solutions
pop[0:k+m] = pop[0:k+m][np.argsort(-1*pop[0:k+m, n])]
                                                    # Truncating m-last solutions
pop[0:k] = pop[m:m+k]
pop[k:k+m] = 0


In [9]:
pop

array([[ 0.15562871,  0.89003053,  0.3126435 ,  2.69516992],
       [-0.03833753,  0.96995531,  0.62334988,  2.08811847],
       [ 0.0987393 ,  0.87869925,  0.71029121,  1.7220532 ],
       [ 0.74925347,  0.83547326,  0.24861916,  1.3610818 ],
       [ 0.67350563,  0.86593774,  1.32216971,  0.01915094],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [10]:

max_iter = 1
for loop in range(max_iter):
  for i in range(k,k+m):
    for j in range(0,n):
                                                      # Choose a based-solution among k solutions
      index = RouletteWheelSelection(sel_prob)
                                                      # Calculate expectation and standard deviation 
      mu = pop[index, j]
      sigma = si * (np.sum(np.absolute(np.subtract(pop[0:k, j], mu)))/(k-1))
                                                      # Calculate S_ij
      pop[i,j] = np.random.normal(mu, sigma)
                                                      # Calculate fitness values
  pop[i, n] = Cost(pop[i, 0:n])
                                                      # Sorting k+m solutions
  pop[0:k+m] = pop[0:k+m][np.argsort(-1*pop[0:k+m, n])]
                                                      # Truncating m-last solutions
  pop[0:k] = pop[m:m+k]
  pop[k:k+m] = 0

print(pop)


[[0.74925347 0.83547326 0.24861916 1.3610818 ]
 [0.43126276 0.90196182 0.95288306 0.5096423 ]
 [0.67350563 0.86593774 1.32216971 0.01915094]
 [0.65848232 0.81941325 0.28687942 0.        ]
 [0.60442229 0.8320464  0.59179459 0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
